import { Type } from 'class-transformer';
import {
  IsInt,
  IsNumber,
  IsOptional,
  IsString,
  IsUUID,
  Max,
  MaxLength,
  Min,
  MinLength,
} from 'class-validator';

/**
 * Payload required to create a work order associated with an existing vehicle.
 *
 * The order number is generated by the backend to avoid relying on client-side
 * numbering.
 */
export class CreateWorkOrderDto {
  @IsUUID()
  vehicleId!: string;

  @IsString()
  @MinLength(5)
  @MaxLength(500)
  reportedIssue!: string;

  @IsOptional()
  @IsString()
  @MaxLength(500)
  diagnosis?: string;

  @IsOptional()
  @IsString()
  @MaxLength(800)
  workDone?: string;

  @IsOptional()
  @IsString()
  @MaxLength(500)
  partsUsed?: string;

  @IsOptional()
  @Type(() => Number)
  @IsInt()
  @Min(0)
  @Max(2000000)
  entryMileage?: number;

  @IsOptional()
  @Type(() => Number)
  @IsNumber()
  @Min(0)
  laborCost?: number;

  @IsOptional()
  @Type(() => Number)
  @IsNumber()
  @Min(0)
  partsCost?: number;

  @IsOptional()
  @Type(() => Number)
  @IsNumber()
  @Min(0)
  estimatedTotal?: number;

  @IsOptional()
  @Type(() => Number)
  @IsNumber()
  @Min(0)
  finalTotal?: number;

  @IsOptional()
  @IsString()
  @MaxLength(500)
  notes?: string;
}