import { Type } from 'class-transformer';
import {
  IsInt,
  IsNumber,
  IsOptional,
  IsString,
  IsUUID,
  Max,
  MaxLength,
  Min,
  MinLength,
} from 'class-validator';

const MAX_MILEAGE = 2000000;
const MAX_MONEY_VALUE = 9999999999.99;

/**
 * Payload required to create a work order associated with an existing vehicle.
 *
 * The order number is generated by the backend to avoid relying on client-side
 * numbering.
 */
export class CreateWorkOrderDto {
  @IsUUID()
  vehicleId!: string;

  @IsString()
  @MinLength(5)
  @MaxLength(500)
  reportedIssue!: string;

  @IsOptional()
  @IsString()
  @MaxLength(1000)
  diagnosis?: string;

  @IsOptional()
  @IsString()
  @MaxLength(1000)
  workDone?: string;

  @IsOptional()
  @IsString()
  @MaxLength(2000)
  partsUsed?: string;

  @IsOptional()
  @Type(() => Number)
  @IsInt()
  @Min(0)
  @Max(MAX_MILEAGE)
  entryMileage?: number;

  @IsOptional()
  @Type(() => Number)
  @IsNumber({ allowInfinity: false, allowNaN: false, maxDecimalPlaces: 2 })
  @Min(0)
  @Max(MAX_MONEY_VALUE)
  laborCost?: number;

  @IsOptional()
  @Type(() => Number)
  @IsNumber({ allowInfinity: false, allowNaN: false, maxDecimalPlaces: 2 })
  @Min(0)
  @Max(MAX_MONEY_VALUE)
  partsCost?: number;

  @IsOptional()
  @Type(() => Number)
  @IsNumber({ allowInfinity: false, allowNaN: false, maxDecimalPlaces: 2 })
  @Min(0)
  @Max(MAX_MONEY_VALUE)
  estimatedTotal?: number;

  @IsOptional()
  @Type(() => Number)
  @IsNumber({ allowInfinity: false, allowNaN: false, maxDecimalPlaces: 2 })
  @Min(0)
  @Max(MAX_MONEY_VALUE)
  finalTotal?: number;

  @IsOptional()
  @IsString()
  @MaxLength(800)
  notes?: string;
}
